version: '3'

services:
  db:
    container_name: custom-rss-postgres
    image: postgres:13
    restart: always
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: customrss
      POSTGRES_USER: customrss
      POSTGRES_PASSWORD: CustomRSS!867d-2c0f87f874a0
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - database:/var/lib/postgresql/data/pgdata

  web:
    container_name: custom-rss-python
    build: .
    ports:
      - "8001:8000"
    depends_on:
      - db
    volumes:
      - .:/app:rw

volumes:
  database: