version: '3'

services:
  db:
    container_name: custom-rss-postgres
    image: postgres:13
    restart: always
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: db
      POSTGRES_USER: postgres-user
      POSTGRES_PASSWORD: my-pass
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - database:/var/lib/postgresql/data/pgdata

  web:
    container_name: custom-rss-python
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - db
    volumes:
      - .:/app:rw

volumes:
  database: